<a href="https://colab.research.google.com/github/visiont3lab/deep-learning-course/blob/main/colab/Class_Python_Recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics

## List, Pandas

In [139]:
!pip install names==0.3.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [140]:
import names
import numpy as np

# 40 name surname age
name_list = []
surname_list = []
age_list = []
for i in range(0,500):
  name = names.get_first_name()
  surname = names.get_last_name()
  age = np.random.randint(30,40,1)[0]
  v = f"{name},{surname},{age}"
  
  name_list.append(name)
  surname_list.append(surname)
  age_list.append(age)

# Key, Value
table = {
    "name": name_list,
    "surname": surname_list,
    "age": age_list
}

# Library Pandas 
# Dictionary--> Excel , csv file
import pandas as pd
df = pd.DataFrame(table)
df.to_excel("test.xlsx", index=None)
df.to_csv("test.csv", index=None)


In [141]:
a = pd.read_excel("test.xlsx")
a = pd.read_csv("test.csv")

## Visualization

In [143]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv")

#import matplotlib.pyplot as plt
#fig = plt.figure()
#plt.plot(df["data"].values, df["dimessi_guariti"].values)
#plt.plot(df["data"].values, df["totale_positivi"].values)
#plt.show()

# plotly
import  plotly.graph_objects as go
fig = go.Figure()
fig.add_traces( go.Scatter(x=df["data"], y=df["dimessi_guariti"] , name="dimessi guariti") )
fig.add_traces( go.Scatter(x=df["data"], y=df["totale_positivi"] , name="totale positivi") )
fig.update_layout(
    title="Dati andamento nazionale",
    paper_bgcolor="black",
    plot_bgcolor="grey",
    hovermode="x"
)
fig.show()
#fig.write_html("data.html")

## Schedule

In [ ]:
!pip install schedule

In [145]:
import pandas as pd

def get_data(i, c, p, o=4, test=2):
  t = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv")
  l = ["deceduti","totale_positivi","dimessi_guariti","totale_casi"]
  index = 110
  print(f"data: {t['data'].values[index]}")
  for el in l:
    print("-------------------")
    print(f"{el}: {t[el].values[index]}")
    print(f"{el} incremento: {t[el].values[index-1]-t[el].values[index]}")
  return 4, [4,5,5], (4,4)

a, b, c = get_data(5,6,4)
print(a,b,c)
#display(t)
#print(t.keys())
#print(t.keys())

#print("totale positivi oggi: ", list(t["totale_positivi"])[-1])
#np.abs(t["totale_positivi"].values[-1]-t["totale_positivi"].values[-2])

data: 2020-06-13T17:00:00
-------------------
deceduti: 34301
deceduti incremento: -78
-------------------
totale_positivi: 27485
totale_positivi incremento: 1512
-------------------
dimessi_guariti: 174865
dimessi_guariti incremento: -1780
-------------------
totale_casi: 236651
totale_casi incremento: -346
4 [4, 5, 5] (4, 4)


In [ ]:
import schedule
import time

schedule.every(5).seconds.do(get_data)
#schedule.every(10).minutes.do(job)
#schedule.every().hour.do(job)
#schedule.every().day.at("19:52").do(job)

while 1:
    schedule.run_pending()
    time.sleep(1)

## Numpy

In [147]:
import numpy as np
v = np.array([
    [4,4,5],
    [3,5,6]
  ], dtype=float)
a = np.array([
    [4,4,5],
    [3,5,6],
    [3,5,6]
  ], dtype=float)

print(v.shape)
# 2x3 3x3 --> 2x3
m = np.matmul( v, a  )

print(m)
m[:,2][1]


(2, 3)
[[43. 61. 74.]
 [45. 67. 81.]]


81.0

## Torch

In [148]:
import torch
import numpy as np
s = np.array([3,5,6], dtype=float)
p = torch.tensor([[3,5,6]], dtype=float) # 1x3
a = torch.tensor([
    [3,5],
    [3,5],
    [3,5],
    ], dtype=float) #3x2

gpu_device = torch.device("cuda:0")
cpu_device = torch.device("cpu")
p = p.to(gpu_device)
a = a.to(gpu_device)
m = torch.matmul(p,a)
#a = a.to(cpu_device)
a.cpu().numpy()


array([[3., 5.],
       [3., 5.],
       [3., 5.]])