<a href="https://colab.research.google.com/github/visiont3lab/deep-learning-course/blob/main/colab/ExcerciseNetworkPytorchNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn
import numpy as np

# Network 7 input 4 neuron and 1 output neuron

class MyNet:
  def __init__(self):
    self.WI = np.random.randn(4,7)
    self.BI = np.random.randn(4,1)
    self.WO = np.random.randn(1,4)
    self.BO = np.random.randn(1,1)
  def forward(self,X):
    V = self.sigmoid( np.matmul( self.WI,X) + self.BI )
    Y = np.matmul( self.WO,V) + self.BO
    return Y
  def sigmoid(self,X):
    return 1/1+np.exp(-X)

X = np.array(
    [
      [4,6,7,8,4,5,6],
      [4,6,7,8,4,5,6]
    ]
  , dtype=np.int32).T

test1 = MyNet()
Y_est1 = test1.forward(X)
print(Y_est1)

class Net(nn.Module):
    def __init__(self):
      super(Net,self).__init__()
      self.fc1 = nn.Linear(7,4)
      #self.fc1.weight = torch.nn.parameter.Parameter(torch.from_numpy(np.random.randn(7,4)))
      #self.fc1.bias = torch.nn.parameter.Parameter(torch.from_numpy(np.random.randn(4,1)))
      
      self.fc2 = nn.Linear(4,1)
      #self.fc2.weight = torch.nn.parameter.Parameter(torch.from_numpy(np.random.randn(1,4)))
      #self.fc2.bias = torch.nn.parameter.Parameter(torch.from_numpy(np.random.randn(1,1)))
      
    def forward(self,x):
      x = torch.tensor(x, dtype=torch.float32)
      x = torch.sigmoid(self.fc1(x))
      y = self.fc2(x)
      return y

test2 = Net()
Xt = torch.from_numpy(X.T)
Y_est2 = test2.forward(Xt)
print(Y_est2)

# visualize weights and bias of pytorch net module
for name, param in test2.named_parameters():
    print(name, param)

[[3.02307096e+09 3.02307096e+09]]
tensor([[-0.3087],
        [-0.3087]], grad_fn=<AddmmBackward0>)
fc1.weight Parameter containing:
tensor([[ 0.0988, -0.3386,  0.1106,  0.2515, -0.1808, -0.1665,  0.0288],
        [-0.2769,  0.3245, -0.2338,  0.1254, -0.1122, -0.2932,  0.1477],
        [ 0.2950, -0.3360,  0.1893,  0.1164,  0.3361,  0.0937,  0.1796],
        [ 0.1710,  0.3009,  0.2604,  0.0302, -0.1713,  0.3183, -0.0076]],
       requires_grad=True)
fc1.bias Parameter containing:
tensor([ 0.1896, -0.2248,  0.1434, -0.2363], requires_grad=True)
fc2.weight Parameter containing:
tensor([[ 0.1830, -0.0124, -0.4345, -0.1176]], requires_grad=True)
fc2.bias Parameter containing:
tensor([0.1515], requires_grad=True)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:43: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


In [2]:
import numpy as np

# feedforward step

def f(x):
  return 1.0 / 1.0 + np.exp(-x)
# rows number: number of neurons, 
# number of columns: is the number of input

WI = np.array(
            [
              [4,23,3],
              [3,4,3],
              [2,4,3],
              [22,24,23],
            ])

BI = np.array([4,5,6,7]).reshape(-1,1)

WII = np.array(
            [
              [4,23,4,5],
              [3,4,5,6],
            ])

BII = np.array([4,5]).reshape(-1,1)


WO = np.array(
            [
              [4,23],
            ])
BO = np.array([4]).reshape(1,-1)

X = np.array([
              [1,2,3],
              [3,2,4],
              [3,2,4],
              [3,2,4],
              [3,2,4],
              [3,2,4],
              [3,2,4],
              [3,2,4],
              [3,2,4],
              [3,2,4],
            ]
            ).T
print(X.shape)

print(WI.shape)
#print(W.shape,  X.shape, B.shape)

# X --> Y --> Feedforward step
V = f( np.matmul( WI, X  ) + BI)
V = f( np.matmul( WII, V  ) + BII)
Y = np.matmul(WO, V) + BO

print(Y)

(3, 10)
(4, 3)
[[31. 31. 31. 31. 31. 31. 31. 31. 31. 31.]]
