<a href="https://colab.research.google.com/github/visiont3lab/deep-learning-course/blob/main/colab/Python_Recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started With Python for Deep Learning



* [PyTorch Computer Vision Cookbook](https://github.com/PacktPublishing/PyTorch-Computer-Vision-Cookbook)
* [Nerual Network from sctract](https://www.kickstarter.com/projects/sentdex/neural-networks-from-scratch-in-python?lang=it)
* [Programming Pytorch for Deep Learning](https://www.amazon.it/Programming-Pytorch-Deep-Learning-Applications/dp/1492045357)
* [Deep Learning Sample Code](https://github.com/PacktPublishing)

## Google Colab

* Server  (Sistema Operativo) Linux (Ubuntu 18.04)
* Google colaboraty --> PC fornito da google 12.72 GB RAM, Disco Rigido > 15 GB --> GPU Settare il Runtime Type a GPU (Training)

* [Markdown Commands](https://visiont3lab.github.io/tecnologie_data_science/docs/programming/google_colab.html)

---



### Bash basic requirements

In [ ]:
# Elencare i file in una cartella
#!ls 
# Percorso file
#!pwd
# Rimuovere una cartella
#!rm -rf dataset 
# Creare una cartella
#!mkdir -p dataset
# Creare un file
#!touch dataset/manuel.txt
# Muoverci all'interno di una cartella
#%cd .. 

# --- Esercizio
# Create una cartella data
# Inserite nella cartella data un file a.txt, b.txt
# Eleminate il file b.txt
# Eliminate la cartella data

/content


## Python Basic Requirements

* Tuple
* List
* array
* dictionary
* function
* class
* python packages and pip

In [ ]:
# python è un linguaggio interpretato
# Script language --> alto livello

# Lista --> non hanno una dimensione fissa
lista_python = [2,3,4,5,6,"ciao"]
print("lunghezza lista: ", len(lista_python))
nuova_lista = []
for m in lista_python:
    #print(m)
    nuova_lista.append(m)

print(nuova_lista)

lunghezza lista:  6
[2, 3, 4, 5, 6, 'ciao']


In [ ]:
# Importare una libreria
import numpy  as np
# array hanno una dimensione fissa
a = np.random.randint(10,30,1)*np.ones((1,5),dtype=np.float32)
print(a.shape,a.dtype)
print(a)

(1, 5) float64
[[27. 27. 27. 27. 27.]]


In [ ]:
# Creare un array
l = [7,6,10,8]
#l.sort(reverse=True)
arr = np.array(l,dtype=np.float32)
#arr
arr_sort = np.sort(arr)
arr_sort

array([ 6.,  7.,  8., 10.], dtype=float32)

In [ ]:
def my_function(a):
    return a*2
m = my_function(10)
print(m)    

20


In [ ]:
# Esercizio
lista_python = [12,13,"kl", 2,56,8,"ciao"]
Data una lista crea una funzione che mi ritorna un array che contiene i numeri ordinati
--> array[2,8,12,13,56] --> shape (1,5) --> (5,)

In [ ]:
Python + Libreria sul tuo pc --> jupyter notebook -> interfaccia web --> ambient virtuale 
Python + libreria sul pc google --> jupyter notebook -> interfaccia google web --> ambient virtuale 
# ip:port

In [ ]:
# Rimuovere string da una lista
# float , int, string, object
lista_python = [12,13,"kl", 2.3, "Klk", 56.898,8.0,"o"]
def my_function(lista):
    nlist = []
    for el in lista:
        if type(el) is not str:
            nlist.append(el)
    nlist.sort()
    arr =  np.array(nlist, dtype=np.float) 
    arr_round = np.round( np.array(nlist, dtype=np.float), 0 )
    #print(arr.shape)
    return arr, arr_round
notround, round = my_function(lista_python) 
print(notround, round)

[ 2.3    8.    12.    13.    56.898] [ 2.  8. 12. 13. 57.]


In [ ]:
lista_python = [12,13,"kl", 2,56,8.0,"o"]
lista_python.remove("kl")
lista_python.remove("o")
arr = np.array(lista_python)
arr = np.sort(arr)
print(arr)
arr = arr.reshape(1,5)
print(arr)

[ 2.  8. 12. 13. 56.]
[[ 2.  8. 12. 13. 56.]]


In [ ]:
# pandas 
# key - valore
d = { 
        "size" : [64,64,3],
        "training" : np.array([45,6,7]), 
        "training_lr" : 0.5,
        "testing" : [4,65,7],    
    }
d["app"] = ["lò" ,4]
d

{'app': ['lò', 4],
 'size': [64, 64, 3],
 'testing': [4, 65, 7],
 'training': array([45,  6,  7]),
 'training_lr': 0.5}

In [ ]:
h,w,c = (64,64,3)
b = {"klk" : 5}
c = [5,6,7,8]
print(a,b,c)

(64, 64, 3) {'klk': 5} [5, 6, 7, 8]


In [ ]:
d,e,f,g = a
print(d,e,f,g)

5 6 7 8


In [ ]:
# !python --version  # check python version
# data analisi pandas, matplotlib, plotly, seaborn,
# machine learning: scikit-learn
# deep learning : tensorflow (+ keras) (google) [deploy] , pytorch (facebook) [educazione]
# image processing: Pillow, opencv-python (image processing)
#!pip list | grep torch
#!pip install torch 
#!pip uninstall torch 
#!pip install tensorflow==2.4.1
#!pip list | grep tensorflow
#!python --version #--> 3.8 --> tensortflow pytorch

Python 3.7.10


## Pytorch: Installation

* Local (Own Pc)

    Install [python 3.8](https://www.python.org/downloads/)

    ```
    pip3 install virtualenv
    virtualenv env
    source env/bin/activate # Linux - Mac
    source env/Scripts/activate # Windows
    pip install torch torchvision
    ```


* Google Colab

    ```
    pip3 install torch torchvision
    ```
These requirements should be arealdy satisied


In [ ]:
!nvidia-smi

Thu Mar  4 19:26:57 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Verify installation
!pip list | grep torch

torch                         1.7.1+cu101   
torchsummary                  1.5.1         
torchtext                     0.3.1         
torchvision                   0.8.2+cu101   


In [ ]:
# Change runtime colab type to enable GPU
# Click on Runtime --> Select Change Runtime Type --> Select Hardware Accelarion GPU

import torch
import torchvision
print("Torch Version: ",torch.__version__)
print("Torch Vision Version:", torchvision.__version__)
print("Is Cuda available: ", torch.cuda.is_available())
print("Number of  Cuda device: ", torch.cuda.device_count())
print("Get Cuda Current device: ", torch.cuda.current_device())
print("Get Name of Cuda  device: ", torch.cuda.get_device_name(0))

Torch Version:  1.7.1+cu101
Torch Vision Version: 0.8.2+cu101
Is Cuda available:  True
Number of  Cuda device:  1
Get Cuda Current device:  0
Get Name of Cuda  device:  Tesla P100-PCIE-16GB


In [ ]:
torch.cuda.is_available()

True

In [ ]:
! pip3 install torch torchvision

## Pytorch: Tensors

> Tensor: n-dimensional array

* [Pytoch documentation](https://pytorch.org/docs/stable/index.html)
* [List of Pytorch Type](https://pytorch.org/docs/stable/tensors.html)

In [ ]:
import torch
import numpy as np
x = torch.ones((4,4), dtype=torch.float16)
#x = np.ones((4,4), dtype=np.float16)
print(x)
print("Shape: ", x.shape)
print("Type : ", x.dtype) # Torch default data type is torch.float32

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float16)
Shape:  torch.Size([4, 4])
Type :  torch.float16


In [ ]:
# Specify tensor type
x = 2*torch.ones((1,3,2), dtype=torch.int8)
print(x)
print("Shape: ", x.shape)
print("Type : ", x.dtype)

tensor([[[2, 2],
         [2, 2],
         [2, 2]]], dtype=torch.int8)
Shape:  torch.Size([1, 3, 2])
Type :  torch.int8


In [ ]:
# Change tensor type
x = torch.rand(3, dtype=torch.float32) # random uniform 0-1
x = 5*x # Multiply by 5
print("Tensor: %s , Type: %s " % (x, x.dtype))
x = x.type(torch.uint8) # change data type to unit8
print("Tensor: %s , Type: %s " % (x, x.dtype))

Tensor: tensor([3.8648, 3.3090, 3.7264]) , Type: torch.float32 
Tensor: tensor([3, 3, 3], dtype=torch.uint8) , Type: torch.uint8 


In [ ]:
# Tensor to numpy array
x = torch.sin( torch.rand(4) + 2*torch.rand(4) )
xnp = x.numpy()
print("Numpy Array: %s , Type: %s " % (xnp, xnp.dtype))

Numpy Array: [0.9982301 0.6028976 0.7176252 0.8889904] , Type: float32 


In [ ]:
# Numpy array to tensor
import numpy as np
xnp = np.sin( np.random.rand(4) + 2*np.random.rand(4) ) # Float64 by default numpy
print(xnp)
x = torch.from_numpy(xnp)
x = x.type(torch.float32)
print("Tensor: %s , Type: %s " % (x, x.dtype))

[0.87555113 0.62579561 0.79933828 0.97127132]
Tensor: tensor([0.8756, 0.6258, 0.7993, 0.9713]) , Type: torch.float32 


In [ ]:
# Moving tensor bettwen cpu and cuda device
# If u do not specify the device the tensorf will be hosted by default on cpu
x = torch.tensor([[1,3,4.4,5.6]]) # RAM
print("Tensor: %s , Type: %s ,Shape: %s, Device: %s" % (x.tolist(), x.dtype,x.shape,x.device))
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    x = x.to(device)
    print("Tensor: %s , Type: %s ,Shape: %s, Device: %s" % (x.tolist(), x.dtype,x.shape,x.device))


Tensor: [[1.0, 3.0, 4.400000095367432, 5.599999904632568]] , Type: torch.float32 ,Shape: torch.Size([1, 4]), Device: cpu
Tensor: [[1.0, 3.0, 4.400000095367432, 5.599999904632568]] , Type: torch.float32 ,Shape: torch.Size([1, 4]), Device: cuda:0


In [ ]:
class myclass: # la classe è un contenitore (diverse funzioni)
    def __init__(self, lista):
        # Initial
        self.arr = np.array(lista, dtype=np.float32)
        #self.device = torch.device("cuda:0")
        self.device = torch.device("cpu")
        
    def arrayToTensor(self):
        x = torch.from_numpy(self.arr).to(self.device)
        return x
    def arrayDouble(self):
        x = self.arr*2
        return x
        
cl = myclass([5,7,8,9])
p1 = cl.arrayToTensor()
p2  = cl.arrayDouble()
print(p1.device,p2)

cr = myclass([5,16,2,9])
pr1 = cr.arrayToTensor()
pr2  = cr.arrayDouble()
print(pr1,pr2)