<a href="https://colab.research.google.com/github/visiont3lab/deep-learning-course/blob/main/colab/Python_RecapClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started With Python for Deep Learning



* [PyTorch Computer Vision Cookbook](https://github.com/PacktPublishing/PyTorch-Computer-Vision-Cookbook)
* [Nerual Network from sctract](https://www.kickstarter.com/projects/sentdex/neural-networks-from-scratch-in-python?lang=it)
* [Programming Pytorch for Deep Learning](https://www.amazon.it/Programming-Pytorch-Deep-Learning-Applications/dp/1492045357)
* [Deep Learning Sample Code](https://github.com/PacktPublishing)

## Google Colab

* Server  (Sistema Operativo) Linux (Ubuntu 18.04)
* Google colaboraty --> PC fornito da google 12.72 GB RAM, Disco Rigido > 15 GB --> GPU Settare il Runtime Type a GPU (Training)

* [Markdown Commands](https://visiont3lab.github.io/tecnologie_data_science/docs/programming/google_colab.html)

---



In [ ]:
a=5
a+6

11

# Titolo
## Sottotilo

* ds
* ds
* fsd

1. d
2. 34
3. ds

**sfsdf**

fsdf fdsf
fdsfds 
fdsfsd
```python
import numpy as np
```



In [ ]:
#!ls
#%cd /content
#!ls
#!mkdir -p ciao
!rm -rf ciaoo
# !mkdir --help

In [ ]:
!python --version

Python 3.7.10


In [ ]:
#!pip install -r requirments.txt
#!pip list > t.txt

In [ ]:
!pip list | grep pandas

pandas                        1.2.3         
pandas-datareader             0.9.0         
pandas-gbq                    0.13.3        
pandas-profiling              1.4.1         
sklearn-pandas                1.8.0         


In [ ]:
!pip uninstall pandas #==1.2.3

### Bash basic requirements

In [ ]:
# Elencare i file in una cartella
#!ls 
# Percorso file
#!pwd
# Rimuovere una cartella
#!rm -rf dataset 
# Creare una cartella
#!mkdir -p dataset
# Creare un file
#!touch dataset/manuel.txt
# Muoverci all'interno di una cartella
#%cd .. 

# --- Esercizio
# Create una cartella data
# Inserite nella cartella data un file a.txt, b.txt
# Eleminate il file b.txt
# Eliminate la cartella data

/content


## Ripasso

In [ ]:
!pip list | grep torchvision

torchvision                   0.9.1+cu101   


In [ ]:
import numpy as np # algebra --> matlab
import pandas as pd # manipolazione (prendere file da csv, xcel)
import torch #  pytorch
import torchvision # pytorch

# lista ha lunghezza variabile
# una lista è iterabile

# array ha una dimensione finita (shape)
# operazioni algebriche


p = ["kl",2, [3,4,5,6], "d",{"l": 5}]
m = ["l", "k", "k", "k", "k"]
p.insert(2, ["ciao"])
p.append([3,4,5])
for elp,elm in zip(p,m):
    print(elp,elm)


#print(len(p))
#print(p)

a = np.array([[4.6,7,9.7]])
#print(a.shape)
#display(a)
#print(a)
#b = np.array([3,4])

kl l
2 k
['ciao'] k
[3, 4, 5, 6] k
d k


In [ ]:
a = np.array([
              [3,4,5],
              [2.3,5,6]
            ])
a[:,:-1]

array([[3. , 4. ],
       [2.3, 5. ]])

In [ ]:
img1 = np.ones((10,3,128,128)) # BCHW
r = img1[2,0,:,:]
g = img1[2,1,:,:]
b = img1[2,2,:,:]

img2 = 2*np.zeros((3,128,128)) # ones, zeros
img3 = 3*np.ones((3,128,128))
img4 = 4*np.ones((3,128,128))
imgs = [img1,img2,img3,img4]
for img in imgs:
    print(img.max())

1.0
0.0
3.0
4.0


In [ ]:
m = np.random.randn(1,3,128,128)
print(m.min())
print(m.max())


-4.143691887429908
4.040349122101629


In [ ]:
for row in range(0,a.shape[0]):
    for col in range(0,a.shape[1]):
        print(a[row,col])

3.0
4.0
5.0
2.3
5.0
6.0


In [ ]:
a = np.array([
              [3,60,5],
              [2.3,3,6],
              [200,300,600],
            ])
a = a[np.newaxis,np.newaxis,:,:,np.newaxis]
#print(a.shape)

def stampa(a):
    m = []
    for row in range(0,a.shape[0]):
        for col in range(0,a.shape[1]):
            m.append(a[row,col])
    return m, 5, [3,3]

l,k,j = stampa(a)
print(l)
print(k,j)

[array([[[  3. ],
        [ 60. ],
        [  5. ]],

       [[  2.3],
        [  3. ],
        [  6. ]],

       [[200. ],
        [300. ],
        [600. ]]])]
5 [3, 3]


In [ ]:
def test(a,b):
    return a+b, a*b, [a+b, a*b]

sum,moltiplicazione, lista =  test(6,7) 

print(sum)
print(moltiplicazione)
print(lista)

13
42
[13, 42]


In [ ]:
class MyClass:
    def test1(self,a,b):
        return self.j

    def test2(self,a,b):
        return a-b, a/b+self.j, [a-b, a/b] 

a = MyClass()
a.j = 30
print(a.test1(5,6))
b = MyClass()
b.j = 20
print(b.test1(6,3))

In [ ]:
# Dizionari!
a = {
        "nome": ["manuel",";l"],
        "cognome": ["rucci",7], 
    }
a.keys()
a.values()

dict_values([['manuel', ';l'], ['rucci', 7]])

In [ ]:
def casa(a,b,c=5):
    return a+b+c
casa(4,5,1)

10

In [ ]:
import pandas as pd
a = {
        "nomi": ["manuel","ilaria","sara","manuel"],
        "cognomi": ["rucci","mp", "p","s"], 
    }

#print(a["nomi"])
df = pd.DataFrame(a)
#df.to_excel("m.xlsx",index=None)
df["nomi"].unique()

array(['manuel', 'ilaria', 'sara'], dtype=object)

In [ ]:
import json

data = {}
data['people'] = []
data['people'].append({
    'name': 'Scott',
    'website': 'stackabuse.com',
    'from': 'Nebraska'
})
data['people'].append({
    'name': 'Larry',
    'website': 'google.com',
    'from': 'Michigan'
})
data['people'].append({
    'name': 'Tim',
    'website': 'apple.com',
    'from': 'Alabama'
})

with open('data.json', 'w') as outfile:
    json.dump(data, outfile)

In [ ]:
import json

with open('data.json','r') as json_file:
    data = json.load(json_file)
    print(data["people"])

[{'name': 'Scott', 'website': 'stackabuse.com', 'from': 'Nebraska'}, {'name': 'Larry', 'website': 'google.com', 'from': 'Michigan'}, {'name': 'Tim', 'website': 'apple.com', 'from': 'Alabama'}]


In [ ]:
ww,hh = [640,480]
hh

a = set(["manuel", "klk", "lkl", "manuel"])
a

{'klk', 'lkl', 'manuel'}

## Python Basic Requirements

* Tuple
* List
* array
* dictionary
* function
* class
* python packages and pip

In [ ]:
# python è un linguaggio interpretato
# Script language --> alto livello

# Lista --> non hanno una dimensione fissa
lista_python = [2,3,4,5,6,"ciao"]
print("lunghezza lista: ", len(lista_python))
nuova_lista = []
for m in lista_python:
    #print(m)
    nuova_lista.append(m)

print(nuova_lista)

lunghezza lista:  6
[2, 3, 4, 5, 6, 'ciao']


In [ ]:
# Importare una libreria
import numpy  as np
# array hanno una dimensione fissa
a = np.random.randint(10,30,1)*np.ones((1,5),dtype=np.float32)
print(a.shape,a.dtype)
print(a)

(1, 5) float64
[[27. 27. 27. 27. 27.]]


In [ ]:
# Creare un array
l = [7,6,10,8]
#l.sort(reverse=True)
arr = np.array(l,dtype=np.float32)
#arr
arr_sort = np.sort(arr)
arr_sort

array([ 6.,  7.,  8., 10.], dtype=float32)

In [ ]:
def __my_function__(a):
    return a*2
m = __my_function__(10)
print(m)    

20


In [ ]:
# Esercizio
lista_python = [12,13,"kl", 2,56,8,"ciao"]
Data una lista crea una funzione che mi ritorna un array che contiene i numeri ordinati
--> array[2,8,12,13,56] --> shape (1,5) --> (5,)

In [ ]:
Python + Libreria sul tuo pc --> jupyter notebook -> interfaccia web --> ambient virtuale 
Python + libreria sul pc google --> jupyter notebook -> interfaccia google web --> ambient virtuale 
# ip:port

In [ ]:
# Rimuovere string da una lista
# float , int, string, object
lista_python = [12,13,"kl", 2.3, "Klk", 56.898,8.0,"o"]
def my_function(lista):
    nlist = []
    for el in lista:
        if type(el) is not str:
            nlist.append(el)
    nlist.sort()
    arr =  np.array(nlist, dtype=np.float) 
    arr_round = np.round( np.array(nlist, dtype=np.float), 0 )
    #print(arr.shape)
    return arr, arr_round
notround, round = my_function(lista_python) 
print(notround, round)

[ 2.3    8.    12.    13.    56.898] [ 2.  8. 12. 13. 57.]


In [ ]:
lista_python = [12,13,"kl", 2,56,8.0,"o"]
lista_python.remove("kl")
lista_python.remove("o")
arr = np.array(lista_python)
arr = np.sort(arr)
print(arr)
arr = arr.reshape(1,5)
print(arr)

[ 2.  8. 12. 13. 56.]
[[ 2.  8. 12. 13. 56.]]


In [ ]:
# pandas 
# key - valore
d = { 
        "size" : [64,64,3],
        "training" : np.array([45,6,7]), 
        "training_lr" : 0.5,
        "testing" : [4,65,7],    
    }
d["app"] = ["lò" ,4]
d

{'app': ['lò', 4],
 'size': [64, 64, 3],
 'testing': [4, 65, 7],
 'training': array([45,  6,  7]),
 'training_lr': 0.5}

In [ ]:
h,w,c = (64,64,3)
b = {"klk" : 5}
c = [5,6,7,8]
print(a,b,c)

(64, 64, 3) {'klk': 5} [5, 6, 7, 8]


In [ ]:
d,e,f,g = a
print(d,e,f,g)

5 6 7 8


In [ ]:
a = np.array([6,7,8],dtype=np.float)
a = torch.tensor([6,7,8],dtype=torch.float32)
a

tensor([6., 7., 8.])

In [ ]:
# !python --version  # check python version
# data analisi pandas, matplotlib, plotly, seaborn,
# machine learning: scikit-learn
# deep learning : tensorflow (+ keras) (google) [deploy] , pytorch (facebook) [educazione]
# image processing: Pillow, opencv-python (image processing)
#!pip list | grep torch
#!pip install torch 
#!pip uninstall torch 
#!pip install tensorflow==2.4.1
#!pip list | grep tensorflow
#!python --version #--> 3.8 --> tensortflow pytorch

Python 3.7.10


## Pytorch: Installation

* Local (Own Pc)

    Install [python 3.8](https://www.python.org/downloads/)

    ```
    pip3 install virtualenv
    virtualenv env
    source env/bin/activate # Linux - Mac
    source env/Scripts/activate # Windows
    pip install torch torchvision
    ```


* Google Colab

    ```
    pip3 install torch torchvision
    ```
These requirements should be arealdy satisied


In [ ]:
!nvidia-smi

Tue Apr 13 18:59:26 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Verify installation
!pip list | grep torch

torch                         1.8.1+cu101   
torchsummary                  1.5.1         
torchtext                     0.9.1         
torchvision                   0.9.1+cu101   


In [ ]:
# Change runtime colab type to enable GPU
# Click on Runtime --> Select Change Runtime Type --> Select Hardware Accelarion GPU

import torch
import torchvision
print("Torch Version: ",torch.__version__)
print("Torch Vision Version:", torchvision.__version__)
print("Is Cuda available: ", torch.cuda.is_available())
print("Number of  Cuda device: ", torch.cuda.device_count())
print("Get Cuda Current device: ", torch.cuda.current_device())
print("Get Name of Cuda  device: ", torch.cuda.get_device_name(0))

Torch Version:  1.8.1+cu101
Torch Vision Version: 0.9.1+cu101
Is Cuda available:  True
Number of  Cuda device:  1
Get Cuda Current device:  0
Get Name of Cuda  device:  Tesla T4


In [ ]:
torch.cuda.is_available()

True

In [ ]:
! pip3 install torch torchvision

## Pytorch: Tensors

> Tensor: n-dimensional array

* [Pytoch documentation](https://pytorch.org/docs/stable/index.html)
* [List of Pytorch Type](https://pytorch.org/docs/stable/tensors.html)

In [ ]:
import numpy as np
A= np.ones((4,4))
B = torch.ones((4,4))
B.shape

torch.Size([4, 4])

In [ ]:
import torch
import numpy as np
x = torch.ones((4,4), dtype=torch.float16)
#x = np.ones((4,4), dtype=np.float16)
print(x)
print("Shape: ", x.shape)
print("Type : ", x.dtype) # Torch default data type is torch.float32

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float16)
Shape:  torch.Size([4, 4])
Type :  torch.float16


In [ ]:
# Specify tensor type
x = 2*torch.ones((1,3,2), dtype=torch.int8)
print(x)
print("Shape: ", x.shape)
print("Type : ", x.dtype)

tensor([[[2, 2],
         [2, 2],
         [2, 2]]], dtype=torch.int8)
Shape:  torch.Size([1, 3, 2])
Type :  torch.int8


In [ ]:
# Change tensor type
x = torch.rand(3, dtype=torch.float32) # random uniform 0-1
x = 5*x # Multiply by 5
print("Tensor: %s , Type: %s " % (x, x.dtype))
x = x.type(torch.uint8) # change data type to unit8
print("Tensor: %s , Type: %s " % (x, x.dtype))

Tensor: tensor([1.4643, 3.4013, 4.4163]) , Type: torch.float32 
Tensor: tensor([1, 3, 4], dtype=torch.uint8) , Type: torch.uint8 


In [ ]:
# Tensor to numpy array
x = torch.sin( torch.rand(4) + 2*torch.rand(4) )
xnp = x.numpy()
print("Numpy Array: %s , Type: %s " % (xnp, xnp.dtype))

Numpy Array: [0.9982301 0.6028976 0.7176252 0.8889904] , Type: float32 


In [ ]:
# Numpy array to tensor
import numpy as np
xnp = np.sin( np.random.rand(4) + 2*np.random.rand(4) ) # Float64 by default numpy
print(xnp)
x = torch.from_numpy(xnp)
x = x.type(torch.float32)
print("Tensor: %s , Type: %s " % (x, x.dtype))

[0.87555113 0.62579561 0.79933828 0.97127132]
Tensor: tensor([0.8756, 0.6258, 0.7993, 0.9713]) , Type: torch.float32 


In [ ]:
# Moving tensor bettwen cpu and cuda device
# If u do not specify the device the tensorf will be hosted by default on cpu
x = torch.tensor([[1,3,4.4,5.6]]) # RAM
print("Tensor: %s , Type: %s ,Shape: %s, Device: %s" % (x.tolist(), x.dtype,x.shape,x.device))
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    x = x.to(device)
    print("Tensor: %s , Type: %s ,Shape: %s, Device: %s" % (x.tolist(), x.dtype,x.shape,x.device))


Tensor: [[1.0, 3.0, 4.400000095367432, 5.599999904632568]] , Type: torch.float32 ,Shape: torch.Size([1, 4]), Device: cpu
Tensor: [[1.0, 3.0, 4.400000095367432, 5.599999904632568]] , Type: torch.float32 ,Shape: torch.Size([1, 4]), Device: cuda:0


In [ ]:
class myclass: # la classe è un contenitore (diverse funzioni)
    def __init__(self, lista):
        # Initial
        self.arr = np.array(lista, dtype=np.float32)
        #self.device = torch.device("cuda:0")
        self.device = torch.device("cpu")
        
    def arrayToTensor(self):
        x = torch.from_numpy(self.arr).to(self.device)
        return x
    def arrayDouble(self):
        x = self.arr*2
        return x
        
cl = myclass([5,7,8,9])
p1 = cl.arrayToTensor()
p2  = cl.arrayDouble()
print(p1.device,p2)

cr = myclass([5,16,2,9])
pr1 = cr.arrayToTensor()
pr2  = cr.arrayDouble()
print(pr1,pr2)